name: 'Test workflow'

on:
  push:
    branches: [master]

jobs:
  test_action_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./.github/actions/test-action
        id: hello
        with:
          who-to-greet: 'Suhardi Hablee'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
